services:
  laravel.test:
    build:
      context: './docker/devcontainer'
      dockerfile: Containerfile
    image: 'localhost/frankenphp-sail:php8.5-bookworm'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      GITHUB_COPILOT_TOKEN: '${COPILOT_GITHUB_TOKEN}'
      SUPERVISOR_PHP_USER: root
      XDG_CONFIG_HOME: /app/config
      XDG_DATA_HOME: /app/data
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/app:z'
    networks:
      - sail
    depends_on:
      - redis
      - meilisearch
      - pgsql
  redis:
    image: 'docker.io/bitnami/redis:latest'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    networks:
      - sail
  meilisearch:
    image: 'docker.io/getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - sail
  pgsql:
    image: 'docker.io/library/postgres:18'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/18/docker'
      - './database/create-testing-database.sql:/docker-entrypoint-initdb.d/create-testing-database.sql'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  sail-pgsql:
    driver: local
