/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'oauth.redirect': [
      {
        name: 'provider'
        required: true
      },
    ]
    'oauth.callback': [
      {
        name: 'provider'
        required: true
      },
    ]
    'connected-accounts.destroy': [
      {
        name: 'id'
        required: true
      },
    ]
    'user-password.set': []
    'login': []
    'logout': []
    'password.request': []
    'password.reset': [
      {
        name: 'token'
        required: true
      },
    ]
    'password.email': []
    'password.update': []
    'register': []
    'verification.notice': []
    'verification.verify': [
      {
        name: 'id'
        required: true
      },
      {
        name: 'hash'
        required: true
      },
    ]
    'verification.send': []
    'user-profile-information.update': []
    'user-password.update': []
    'password.confirmation': []
    'password.confirm': []
    'two-factor.login': []
    'two-factor.enable': []
    'two-factor.confirm': []
    'two-factor.disable': []
    'two-factor.qr-code': []
    'two-factor.secret-key': []
    'two-factor.recovery-codes': []
    'terms.show': []
    'policy.show': []
    'profile.show': []
    'other-browser-sessions.destroy': []
    'current-user-photo.destroy': []
    'current-user.destroy': []
    'api-tokens.index': []
    'api-tokens.store': []
    'api-tokens.update': [
      {
        name: 'token'
        required: true
      },
    ]
    'api-tokens.destroy': [
      {
        name: 'token'
        required: true
      },
    ]
    'sanctum.csrf-cookie': []
    'home': []
    'anime.index': []
    'anime.create': []
    'anime.store': []
    'anime.show': [
      {
        name: 'anime'
        required: true
        binding: 'id'
      },
    ]
    'anime.edit': [
      {
        name: 'anime'
        required: true
        binding: 'id'
      },
    ]
    'anime.update': [
      {
        name: 'anime'
        required: true
        binding: 'id'
      },
    ]
    'anime.destroy': [
      {
        name: 'anime'
        required: true
        binding: 'id'
      },
    ]
    'post.create': [
      {
        name: 'anime'
        required: true
        binding: 'id'
      },
    ]
    'post.store': [
      {
        name: 'anime'
        required: true
      },
    ]
    'post.show': [
      {
        name: 'anime'
        required: true
      },
      {
        name: 'post'
        required: true
        binding: 'id'
      },
    ]
    'post.edit': [
      {
        name: 'anime'
        required: true
      },
      {
        name: 'post'
        required: true
        binding: 'id'
      },
    ]
    'post.update': [
      {
        name: 'anime'
        required: true
      },
      {
        name: 'post'
        required: true
        binding: 'id'
      },
    ]
    'post.destroy': [
      {
        name: 'anime'
        required: true
      },
      {
        name: 'post'
        required: true
        binding: 'id'
      },
    ]
    'dashboard': []
  }
}
export {}
