[program:octane]
process_name = %(program_name)s_%(process_num)s
command = php /app/artisan octane:frankenphp --host=0.0.0.0 --port=80 --admin-port=2019
user = root
priority = 1
autostart = true
autorestart = true
stopwaitsecs = 30
stopasgroup = true
killasgroup = true
environment = OCTANE="1"
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
