<?php

return [
    'genres' => [
        'Action',
        'Adventure',
        'Comedy',
        'Drama',
        'Fantasy',
        'Horror',
        'Mystery',
        'Romance',
        'Sci-Fi',
        'Slice of Life',
        'Sports',
        'Supernatural',
        'Thriller',
        'Ecchi',
        'Hentai',
        'Mahou Shoujo',
        'Mecha',
        'Music',
        'Psychological',
        'Seinen',
        'Shoujo',
        'Shounen',
    ],

    'tags' => [
        'Aliens',
        'Amnesia',
        'Anti-Hero',
        'Artificial Intelligence',
        'Assassins',
        'Battle Royale',
        'Coming of Age',
        'Conspiracy',
        'Cultivation',
        'Cyberpunk',
        'Dark Fantasy',
        'Demons',
        'Detective',
        'Dystopian',
        'Educational',
        'Fashion',
        'Food',
        'Gaming',
        'Gender Bender',
        'Ghosts',
        'Gods',
        'Gore',
        'Harem',
        'Historical',
        'Isekai',
        'Karma',
        'Kids',
        'Kuudere',
        'Magic',
        'Martial Arts',
        'Mature',
        'Military',
        'Monsters',
        'Mythology',
        'Ninja',
        'Noir',
        'Otaku Culture',
        'Parallel Universe',
        'Parody',
        'Pirates',
        'Police',
        'Post-Apocalyptic',
        'PTSD',
        'Reincarnation',
        'Revenge',
        'Robots',
        'Royalty',
        'Samurai',
        'School Life',
        'Shapeshifting',
        'Steampunk',
        'Super Power',
        'Superhero',
        'Survival',
        'Swordplay',
        'Tactics',
        'Time Travel',
        'Tragedy',
        'Tsundere',
        'Urban Fantasy',
        'Vampires',
        'Virtual Reality',
        'War',
        'Werewolves',
        'Witches',
        'Yakuza',
        'Yandere',
        'Zombies',
    ],
];
